language: python

python:
  - "3.7"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libpoppler-cpp-dev

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - pipenv-setup check
  - pytype -V $TRAVIS_PYTHON_VERSION
  - pytest
