language: python

python:
  - "3.7"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y poppler-utils

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - pipenv run pytype -V $TRAVIS_PYTHON_VERSION
  - pipenv run pytest
